### ISSUE TITLE
Split large gpt answer

### ISSUE THREAD

**Issue by theurs** [yym68686/md2tgmd#7]
Chatgpt can answer more then 4k chars with markdown and we need to split it correctly for telegram.

It also should handle math records ([latex2unicode](https://pylatexenc.readthedocs.io/en/latest/) ?) - $$ \frac{dx}{d\theta} = r' \cos \theta - r \sin \theta, \quad \frac{dy}{d\theta} = r' \sin \theta + r \cos \theta. $$

**Comment by yym68686** [comment]
Thank you for providing [latex2unicode](https://pylatexenc.readthedocs.io/en/latest/). This is a cool project. Could you provide an example (a ChatGPT response exceeding 4000 characters include math records) so that I can conveniently conduct testing?

In addition, my other [project](https://github.com/yym68686/ChatGPT-Telegram-Bot) has already supported semantic segmentation of text exceeding 4000 characters on Telegram, and it can reasonably split code blocks

**Comment by yym68686** [comment]
Hello, it is now possible to convert mathematical formulas in LaTeX format to Unicode format.
